[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
syn = { version = "2.0.103", features = ["full"] }
lille = { path = ".." }
ordered-float = { workspace = true }
