[package]
name = "lille-ddlog"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1.0.0", features = ["derive"] }
serde_json = "^1.0.0"
differential_datalog = { path = "differential_datalog" }
ordered-float = { workspace = true, features = ["serde"] }
