name: Install DDlog
description: Download and install the DDlog toolchain.
runs:
  using: composite
  steps:
    - name: Run install script
      shell: bash
      run: |
        ./scripts/install_ddlog.sh
