[package]
name = "build_support"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
dotenvy = "0.15.7"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
sha2 = "0.10"
toml = "0.8"

[dev-dependencies]
tempfile = "3"
insta = { version = "1.38.0", features = ["ron"] }
rstest = "0.18.0"
mockall = "0.12.1"
